routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', 'HomeController@welcome')->name('welcome');

Route::match(array('GET','POST'),'/verify-otp', 'UserController@verifyOtp')->name('verify-otp');
Route::group(['middleware' => 'role:super'], function () {
        Route::get('/admin/home','DashboardController@index')->middleware('role:super')->name('admin.home');
        Route::resource('/admin/dashboard','DashboardController')->middleware('role:super');
        Route::get('/admin/contest/running','ContestController@running')->middleware('role:super')->name('contest.running');
        Route::resource('/admin/contest','ContestController')->middleware('role:super');
        Route::resource('/admin/{contest}/prizing','PrizingController')->middleware('role:super');
        Route::resource('/admin/user','UserController')->middleware('role:super');
        Route::resource('/admin/contact','ContactUsController')->middleware('role:super');
        //REDEEM REQUEST
        Route::get('/admin/redeem','RedeemController@index')->middleware('role:super')->name('admin.redeem');
        Route::get('/admin/redeem/pay/{redeem}','RedeemController@pay')->middleware('role:super')->name('admin.redeem.pay');

        Route::get('/admin/contact-us/{id}','ContactUsController@destroy')->middleware('role:super')->name('contact.delete');
        Route::get('/admin/user/delete/{id}','UserController@destroy')->middleware('role:super')->name('user.delete');

        Route::get('/admin/users/block','UserController@blockUsers')->middleware('role:super')->name('users.block');
        Route::get('/admin/users/unblock/{id}','UserController@unBlockUsers')->middleware('role:super')->name('users.UnBlock');
        Route::get('/admin/users/update-balance/{id}','UserController@updateBalance')->middleware('role:super')->name('users.updateBalance');

        // VERIFY OTP
        
    });

Route::get('user/verify', 'UserController@verify')->name('phoneverification.notice');
Route::post('user/verify', 'UserController@verifyOTP')->name('phoneverification.verify');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'verifiedphone'], function () {

        Route::get('/home', 'HomeController@welcome')->name('home');

        Route::get('/contest/{contest}', 'ContestController@contest')->middleware('auth')->name('contest');
        Route::post('/order/transition/{contest}', 'OrderController@order')->middleware('auth')->name('order');
        Route::post('/order/status', 'OrderController@paymentCallback');
        Route::get('/user/contests', 'UserController@myContests')->name('myContests');
        Route::resource('/user', 'UserController');
        Route::get('/user/contest-result/{contest}', 'UserController@contestResult')->name('contestResult');
        Route::get('/user/{user}/earning', 'UserController@myEarning')->name('user.earning');
        Route::resource('/user/redeem', 'RedeemController');
    });
    Route::group(['middleware' => 'ContestJoined'], function () {
        Route::get('/typing/{contest}', 'TypingTestController@index')->name('typing');
        Route::get('/typing/typing-result/{contest}', 'TypingTestController@typingResult')->name('typingResult');
    });
});


Route::get('/contest-details/{id}', 'HomeController@contestDetails')->name('contestDetails');

Route::get('/about-us', 'HomeController@aboutUs')->name('about-Us');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-Us');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::post('/contact/mail', 'HomeController@contactmail')->name('contact-mail');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Emadadly\LaravelUuid\Uuids;

class User extends Authenticatable
{
    use Notifiable;
      use Uuids;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','mobile','account_number','ifsc','otp',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'otp',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'verified_at' => 'datetime',
    ];

    public $incrementing = false;


    public function hasVerified()
    {
        return ! is_null($this->verified_at);
    }

    public function markAsVerified()
    {
        return $this->forceFill([
            'verified_at' => $this->freshTimestamp(),
        ])->save();
    }


    public function contests(){
        return $this->belongsToMany('App\Contest');
    }

    public function typingTests(){
        return $this->hasMany('App\TypingTest');
    }

    public function redeem(){
        return $this->hasMany('App\Redeem');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Contest;
use App\Redeem;
use App\TypingTest;
use Illuminate\Http\Request;
use App\User;
use App\Rules\OtpVerify;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usersList = User::where('is_block',0)->paginate(15);
        return view('admin.users.index', compact('usersList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $title = 'My Profile';
        $user = User::find($id);
        return view('users.profile', compact('user','title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $title = 'Edit Profile';
        return view('users.edit', compact('user','title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->all());
        return redirect()->route('user.show', $user->id)->with('success','Profile updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function blockUsers(){
        $blockedUser = User::where('is_block', 1)->paginate(20);

        return view('admin.users.block', compact('blockedUser'));
    }

    public function unBlockUsers($id){
        $blockedUser = User::where('id', $id)->first();
        $blockedUser->is_block = !$blockedUser->is_block;
        $blockedUser->save();
        return back()->with('message', 'Operation Successfully Completed');
    }

    public function updateBalance($id){
        $results = TypingTest::where('contest_id',$id)->get();
        foreach ($results as $result) :
            $user = User::find($result->user_id);
            $user->balance = $user->balance + $result->amount;
            $user->save();
        endforeach;
        $contest = Contest::find($id);
        $contest->result = 'completed';
        $contest->save();
        return back()->with('success','Result published successfully');
    }

    public function profile(){
        $title = 'My Profile';
        $user = User::find(\Auth::id());
        return view('users.profile', compact('user','title'));
    }

    public function myContests()
    {
        $title = 'My Contests';
        $user = User::find(\Auth::id());
        $contests = $user->contests()->get();
        $contestActive = $user->contests()->where('start_time', '<', \Carbon\Carbon::now())
            ->where('end_time', '>', \Carbon\Carbon::now())
            ->where('status', '1')
            ->get();
        $expired = $user->contests()->where('end_time', '<', \Carbon\Carbon::now())
            ->where('status', '1')
            ->get();
        return view('users.contests', compact('title','user', 'contests','contestActive','expired'));
    }

    public function myEarning($id)
    {
        $title = 'My Earnings';
        $user = User::find($id);
        $redeems = Redeem::where('user_id',$id)->get();
        $redeem_request = Redeem::where(['user_id' => $id, 'status' => 0])->get();
        $redeemed = Redeem::where(['user_id' => $id, 'status' => 1])->get();
        return view('users.earning', compact('title','user', 'redeems','redeem_request','redeemed'));
    }

    public function verify(Request $request)
    {
        return $request->user()->hasVerified()
            ? redirect()->route('home')
            : view('verify-otp');
    }

    public function verifyOTP(Request $request){
        $request->validate([
            'otp' => 'required',
            'otp' => [new OtpVerify],
        ]);

        if ($request->user()->hasVerified()) {
            return redirect()->route('home');
        }

        $request->user()->markAsVerified();

        return redirect()->route('user.show', Auth::user()->id)->with('success', 'Your account successfully verified!');
    }

    public function contestResult(Contest $contest){
        $title = 'Contest Result';
        $rankings = \App\TypingTest::where('contest_id', $contest->id)->orderBy('points','DESC')->get();
        $contest->result = 'in-review';
        $contest->save();
        return view('users.result', compact('contest','title','rankings'));
    }

}

resources/views/users/contests.blade.php
@extends('layouts.users')

@section('page-title', $title)

@section('content')
    <ul class="nav nav-pills mb-3 nav-fill" id="contestsTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all"
               aria-selected="true">All Contests</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="running-tab" data-toggle="tab" href="#running" role="tab"
               aria-controls="running" aria-selected="false">Running Contests</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="expired-tab" data-toggle="tab" href="#expired" role="tab"
               aria-controls="expired" aria-selected="false">Expired Contests</a>
        </li>
    </ul>
    <div class="tab-content" id="contests">
        <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
            <div class="row">
                @foreach ($contests as $contest)
                    @include('contest.contest-grid')
                @endforeach
            </div>
        </div>
        <div class="tab-pane fade" id="running" role="tabpanel" aria-labelledby="running-tab">
            <div class="row">
                @foreach ($contestActive as $contest)
                    @include('contest.contest-grid')
                @endforeach
            </div>
        </div>
        <div class="tab-pane fade" id="expired" role="tabpanel" aria-labelledby="contact-tab">
            <div class="row">
                @foreach ($expired as $contest)
                    @include('contest.contest-grid')
                @endforeach
            </div>
        </div>
    </div>
    @include('contest._leader-board-modal')
@endsection

resources/views/users/earning.blade.php
@extends('layouts.users')

@section('page-title', $title)

@section('content')
    <div class="earning-page py-5">
        <div class="row">

            <div class="col-sm-6">

                <h5 class="section-title">Balance & Redeems</h5>
                <div class="section-content p-3">
                    <div class="balance mt-3">
                        <div class="row">
                            <div class="col-6">
                                <h6 class="mt-2">Total Balance : </h6>
                            </div>
                            <div class="col-6">
                                <div class="d-flex justify-content-between align-items-center">
                                    <strong> &#8377; {!! $user->balance !!}</strong>
                                    <button class="btn btn-success" data-target="#redeem-form" data-toggle="modal">Redeem</button>
                                </div>
                            </div>
                        </div>

                        <div class="redeems-container mt-4">
                            <ul class="nav nav-tabs mb-3" id="redeemTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab"
                                        aria-controls="all"
                                        aria-selected="true">All Redeems</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="requested-tab" data-toggle="tab" href="#requested" role="tab"
                                        aria-controls="requested" aria-selected="false">Requested Redeems</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="completed-tab" data-toggle="tab" href="#completed" role="tab"
                                        aria-controls="completed" aria-selected="false">Completed Redeems</a>
                                </li>
                            </ul>

                            <div class="tab-content" id="redeemTab">

                                <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
                                    <table class="table">
                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Amount</th>
                                            <th scope="col">Requested At</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Redeemed At</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($redeems as $key => $redeem)
                                            <tr>
                                                <th scope="row">{!! $key+1 !!}</th>
                                                <td>&#8377; {!! $redeem->amount !!}</td>
                                                <td><small>{!! $redeem->created_at !!}</small></td>
                                                <td>{!! $redeem->status !!}</td>
                                                <td><small>{!! $redeem->updated_at !!}</small></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="tab-pane" id="requested" role="tabpanel" aria-labelledby="requested-tab">
                                    <table class="table">
                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Amount</th>
                                            <th scope="col">Requested At</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Redeemed At</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($redeem_request as $key => $redeem)
                                            <tr>
                                                <th scope="row">{!! $key+1 !!}</th>
                                                <td>&#8377; {!! $redeem->amount !!}</td>
                                                <td><small>{!! $redeem->created_at !!}</small></td>
                                                <td>{!! $redeem->status !!}</td>
                                                <td><small>{!! $redeem->updated_at !!}</small></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="tab-pane" id="completed" role="tabpanel" aria-labelledby="completed-tab">
                                    <table class="table">
                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Amount</th>
                                            <th scope="col">Requested At</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Redeemed At</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($redeemed as $key => $redeem)
                                            <tr>
                                                <th scope="row">{!! $key+1 !!}</th>
                                                <td>&#8377; {!! $redeem->amount !!}</td>
                                                <td><small>{!! $redeem->created_at !!}</small></td>
                                                <td>{!! $redeem->status !!}</td>
                                                <td><small>{!! $redeem->updated_at !!}</small></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-sm-6">

                <h5 class="section-title">Winnings</h5>
                <div class="sections-content p-3">
                    <table class="table">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Contest</th>
                            <th scope="col">Rank</th>
                            <th scope="col">Points</th>
                            <th scope="col">Winnings</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($user->typingTests as $key => $typingTest)
                            <tr>
                                <th scope="row">{!! $key+1 !!}</th>
                                <td>{!! $typingTest->contest->title !!}</td>
                                <td>{!! ($typingTest->rank == 0) ? '-' : $typingTest->rank !!}</td>
                                <td>{!! $typingTest->points !!}</td>
                                <td>{!! ($typingTest->amount == 0) ? '-' :  '&#8377; '.$typingTest->amount !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

            </div>

        </div>
    </div>
    @include('modals.redeem-form')
@endsection

resources/views/users/edit.blade.php
@extends('layouts.users')

@section('page-title', $title)

@section('content')

    {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'patch','class' => 'py-5' ]) !!}

    <div class="row">

        <div class="col-sm-6">
            <h5 class="section-title mb-3">User Details</h5>
            <div class="form-group row">
                    {!! Form::label('name', 'Name :', ['class' => 'col-sm-3 col-form-label']) !!}
                <div class="col-sm-9">
                    {!! Form::text('name', null, ['class' => 'form-control '.(($errors->has("name")) ? 'is-invalid' : ''),'placeholder' => 'Enter Name']) !!}
                </div>
            </div>
            <div class="form-group row">
                {!! Form::label('email', 'Email :', ['class' => 'col-sm-3 col-form-label']) !!}
                <div class="col-sm-9">
                    {!! Form::text('email', null, ['class' => 'form-control '.(($errors->has("email")) ? 'is-invalid' : ''),'placeholder' => 'Enter Email', 'readonly'=> true]) !!}
                </div>
            </div>
            <div class="form-group row">
                {!! Form::label('mobile', 'Mobile :', ['class' => 'col-sm-3 col-form-label']) !!}
                <div class="col-sm-9">
                    {!! Form::text('mobile', null, ['class' => 'form-control '.(($errors->has("mobile")) ? 'is-invalid' : ''),'placeholder' => 'Enter Mobile', 'readonly'=> true]) !!}
                </div>
            </div>

        </div>

        <div class="col-sm-6">

            <h5 class="section-title mb-3">Accounts Details</h5>
            <div class="form-group row">
                {!! Form::label('account_number', 'A/C Number :', ['class' => 'col-sm-3 col-form-label']) !!}
                <div class="col-sm-9">
                    {!! Form::text('account_number', null, ['class' => 'form-control '.(($errors->has("account_number")) ? 'is-invalid' : ''),'placeholder' => 'Enter A/C Number']) !!}
                </div>
            </div>
            <div class="form-group row">
                {!! Form::label('ifsc', 'IFSC :', ['class' => 'col-sm-3 col-form-label']) !!}
                <div class="col-sm-9">
                    {!! Form::text('ifsc', null, ['class' => 'form-control '.(($errors->has("ifsc")) ? 'is-invalid' : ''),'placeholder' => 'Enter IFSC']) !!}
                </div>
            </div>

        </div>

        <div class="col-12 mt-2 mb-5 text-center">
            {!! Form::submit('Update', ['class' => 'btn btn-success px-5']) !!}
        </div>
    </div>


    {!! Form::close() !!}

@endsection

resources/views/users/profile.blade.php
@extends('layouts.users')

@section('page-title', $title)

@section('content')
    <a href="{{ route('user.edit', Auth::id()) }}" class="btn btn-primary mb-3">Update Profile</a>
    <div class="row">

        <div class="col-sm-6">

            <h5 class="section-title">User Details</h5>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Name :</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$user->name}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Email :</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$user->email}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Mobile :</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$user->mobile}}">
                </div>
            </div>

        </div>

        <div class="col-sm-6">

            <h5 class="section-title">Accounts Details</h5>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">A/C No. :</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$user->account_number}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">IFSC :</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$user->ifsc}}">
                </div>
            </div>

        </div>

    </div>
@stop

resources/views/users/result.blade.php
@extends('layouts.users')

@section('page-title', $title)

@section('content')
    <div class="row contest-details">
        <div class="col-md-12">
            <div class="row">
                <div class="col-xm-12 col-md-12 mb-3">
                    <div class="single-contest">
                        <h4>{!! $contest->title !!}</h4>
                        <p>{!! $contest->description !!}</p>
                    </div>
                    <div class="col-md-12 home-match-card4">
                        <div class="row justify-content-center align-items-center pt-3">
                            <div class="col-sm-6 col-6 text-left ">
                                <small class="text-muted mb-1">Total Prize</small>
                                <h5 class="m-0"><i class="fas fa-rupee-sign"></i> {!! $contest->total_prize !!}</h5>
                            </div>
                            <div class="col-sm-6 col-6 text-right">
                                <small class="text-muted mb-1">Entry</small>
                                <form action="{{route('order',$contest->id)}}" method="post">
                                    <input type="hidden" name="fees" value="{{$contest->entry_fees}}">
                                    @if ((Auth::check() &&  $contest->hasUser(Auth::user()->id)) || ($contest->reg_users == $contest->max_users ))
                                        <button type="submit" class="btn btn-success join" disabled><i class="fas fa-rupee-sign"></i> {{$contest->entry_fees}}</button>
                                    @else
                                        <button type="submit" class="btn btn-success join"><i class="fas fa-rupee-sign"></i> {{$contest->entry_fees}}</button>
                                    @endif
                                </form>
                            </div>
                        </div>
                        <div class="progress mt-3" style="height:8px">
                            <div class="progress-bar bg-gold" style="width:{{ ($contest->reg_users / $contest->max_users) * 100  }}%"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-6 text-left text-gold"><p>{{($contest->max_users - $contest->reg_users)}} soprt left</p></div>
                            <div class="col-sm-6 col-6 text-right text-muted home-prize"><p>{{$contest->max_users}} spots</p></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col text-center mt-3 mb-1">
                    <ul class="nav nav-pills mb-3 nav-fill" id="leaderboardTab" role="tablist">
                        <li class="nav-item">
                            <h5 class="nav-link" id="prize-tab" data-toggle="tab" data-target="#prize" role="tab"
                                aria-controls="prize"
                                aria-selected="true">Prize Breakup</h5>
                        </li>
                        <li class="nav-item">
                            <h5 class="nav-link  active" id="ranking-tab" data-toggle="tab" data-target="#ranking" role="tab"
                                aria-controls="ranking" aria-selected="false">Leaderboard</h5>
                        </li>
                    </ul>
                    {{--<h5>Prize Breakup</h5>--}}
                    <div class="tab-content" id="leaderboard">

                        <div class="tab-pane fade" id="prize" role="tabpanel" aria-labelledby="prize-tab">
                            <table class="table">
                                <tr>
                                    <th>Rank</th>
                                    <th class="text-right">Prize</th>
                                </tr>
                                @foreach ($contest->prizings as $prizing)
                                    <tr>
                                        <td>
                                            # {!! $prizing->rank_from  !!} {!! (($prizing->rank_to != 0) ? ' - '.$prizing->rank_to : '') !!}</td>
                                        <td class="text-right"><i class="fas fa-rupee-sign"></i> {!! $prizing->amount !!}
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                        <div class="tab-pane fade show active" id="ranking" role="tabpanel" aria-labelledby="ranking-tab">
                            <table class="table">
                                <tr>
                                    <th>Users</th>
                                    <th>Points</th>
                                    <th>Rank</th>
                                </tr>
                                @foreach ($rankings as $ranking)
                                    <tr>
                                        <td>{!! $ranking->user->name !!}</td>
                                        <td>{!! $ranking->points !!}</td>
                                        <td>{!! $ranking->rank !!}</td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection