routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', 'HomeController@welcome')->name('welcome');

Route::match(array('GET','POST'),'/verify-otp', 'UserController@verifyOtp')->name('verify-otp');
Route::group(['middleware' => 'role:super'], function () {
        Route::get('/admin/home','DashboardController@index')->middleware('role:super')->name('admin.home');
        Route::resource('/admin/dashboard','DashboardController')->middleware('role:super');
        Route::get('/admin/contest/running','ContestController@running')->middleware('role:super')->name('contest.running');
        Route::resource('/admin/contest','ContestController')->middleware('role:super');
        Route::resource('/admin/{contest}/prizing','PrizingController')->middleware('role:super');
        Route::resource('/admin/user','UserController')->middleware('role:super');
        Route::resource('/admin/contact','ContactUsController')->middleware('role:super');
        //REDEEM REQUEST
        Route::get('/admin/redeem','RedeemController@index')->middleware('role:super')->name('admin.redeem');
        Route::get('/admin/redeem/pay/{redeem}','RedeemController@pay')->middleware('role:super')->name('admin.redeem.pay');

        Route::get('/admin/contact-us/{id}','ContactUsController@destroy')->middleware('role:super')->name('contact.delete');
        Route::get('/admin/user/delete/{id}','UserController@destroy')->middleware('role:super')->name('user.delete');

        Route::get('/admin/users/block','UserController@blockUsers')->middleware('role:super')->name('users.block');
        Route::get('/admin/users/unblock/{id}','UserController@unBlockUsers')->middleware('role:super')->name('users.UnBlock');
        Route::get('/admin/users/update-balance/{id}','UserController@updateBalance')->middleware('role:super')->name('users.updateBalance');

        // VERIFY OTP
        
    });

Route::get('user/verify', 'UserController@verify')->name('phoneverification.notice');
Route::post('user/verify', 'UserController@verifyOTP')->name('phoneverification.verify');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'verifiedphone'], function () {

        Route::get('/home', 'HomeController@welcome')->name('home');

        Route::get('/contest/{contest}', 'ContestController@contest')->middleware('auth')->name('contest');
        Route::post('/order/transition/{contest}', 'OrderController@order')->middleware('auth')->name('order');
        Route::post('/order/status', 'OrderController@paymentCallback');
        Route::get('/user/contests', 'UserController@myContests')->name('myContests');
        Route::resource('/user', 'UserController');
        Route::get('/user/contest-result/{contest}', 'UserController@contestResult')->name('contestResult');
        Route::get('/user/{user}/earning', 'UserController@myEarning')->name('user.earning');
        Route::resource('/user/redeem', 'RedeemController');
    });
    Route::group(['middleware' => 'ContestJoined'], function () {
        Route::get('/typing/{contest}', 'TypingTestController@index')->name('typing');
        Route::get('/typing/typing-result/{contest}', 'TypingTestController@typingResult')->name('typingResult');
    });
});


Route::get('/contest-details/{id}', 'HomeController@contestDetails')->name('contestDetails');

Route::get('/about-us', 'HomeController@aboutUs')->name('about-Us');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-Us');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::post('/contact/mail', 'HomeController@contactmail')->name('contact-mail');

resources/views/elements/admin/breadcrumb.blade.php
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-12">
        <h4 class="m-0 text-dark"> @yield('pageHeader') </h4>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

resources/views/elements/admin/head.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title') - Fantasy Typing</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('assets/plugins/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css')}}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{asset('assets/plugins/iCheck/flat/blue.css')}}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{{asset('assets/plugins/morris/morris.css')}}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{asset('assets/plugins/jvectormap/jquery-jvectormap-1.2.2.css')}}">
  <!-- Date Picker -->
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{asset('assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link rel="stylesheet" href="{{asset('assets/dist/css/bootstrap-datetimepicker.min.css')}}" />
</head>

resources/views/elements/admin/header.blade.php
<nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fa fa-comments-o"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fa fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fa fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fa fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fa fa-bell-o"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fa fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fa fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fa fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
          class="fa fa-th-large"></i></a>
    </li>
  </ul>
</nav>

resources/views/elements/admin/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{{env("APP_URL")}}" class="brand-link">
    <img src="{{asset("assets/dist/img/AdminLTELogo.png")}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{asset("assets/dist/img/user2-160x160.jpg")}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">Alexander Pierce</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="{{route('dashboard.index')}}" class="nav-link {{ (request()->is('admin/dashboard')) ? ' active' : '' }}">
            <i class="nav-icon fa fa-dashboard"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        <li class="nav-item has-treeview {{ (request()->is('admin/contest*')) ? ' menu-open' : '' }}">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-pie-chart"></i>
            <p>
              Contest
              <i class="right fa fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{route('contest.index')}}" class="nav-link {{ (request()->is('admin/contest')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>List</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('contest.running')}}" class="nav-link {{ (request()->is('admin/contest/running')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>Running</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('contest.create')}}" class="nav-link {{ (request()->is('admin/contest/create')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>Create</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview {{ (request()->is('admin/user*')) ? ' menu-open' : '' }}">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-pie-chart"></i>
            <p>
              Users
              <i class="right fa fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{route('user.index')}}" class="nav-link {{ (request()->is('admin/user')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>List</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('users.block')}}" class="nav-link {{ (request()->is('admin/users/block')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>Blocked Users</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview {{ (request()->is('admin/redeem*')) ? ' menu-open' : '' }}">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-pie-chart"></i>
            <p>
              Redeem Request
              <i class="right fa fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{route('admin.redeem')}}" class="nav-link {{ (request()->is('admin/redeem')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>List</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview {{ (request()->is('admin/contact*')) ? ' menu-open' : '' }}">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-pie-chart"></i>
            <p>
              Contact Us
              <i class="right fa fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{route('contact.index')}}" class="nav-link {{ (request()->is('admin/contact')) ? ' active' : '' }}">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>List</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="{{route('admin.logout')}}" class="nav-link" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <i class="nav-icon fa fa-dashboard"></i>
            <p>
              Logout
            </p>
          </a>
          <form id="logout-form" action="{{ route('admin.logout') }}" method="POST"
                style="display: none;">{{ csrf_field() }}</form>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>